### ISSUE TITLE
Results on the MVTec AD？ 

### ISSUE THREAD

**Issue by xiahaifeng1995** [Niousha12/Puzzle_Anomaly_Detection#1]
Hi, thanks for opensourcing this excellent project. Would you have the experimental results on the MVTec ad dataset?

**Comment by Niousha12** [comment]
Hi
Thanks for your interest. Our paper will be submitted on arxiv during next week. There exist results on several datasets including MVTec ad. After that if you had any question I will be glad to be in contact.
RegardsNiousha
    On Wednesday, August 26, 2020, 10:36:23 AM GMT+4:30, haifeng xia <notifications@github.com> wrote:  
 
 


Hi, thanks for opensourcing this excellent project. Would you have the experimental results on the MVTec ad dataset?
