### ISSUE TITLE
About real_label?

### ISSUE THREAD

**Issue by tiandamiao** [Niousha12/Puzzle_Anomaly_Detection#2]
In the train, the label of normal data  is 1.
In the test, if the input is normal sample, the test loss should be relatively small, and if it is abnormal sample, the test loss should be relatively large. The question is: Why are normal samples labeled 1 instead of 0?
I'm confused about this and hope to get your reply.Thank you!

**Comment by Niousha12** [comment]
Hi,
Thanks for your feedback. Label of data in train data filter out normal data from whole dataset, for example if your dataset is mnist and you want to train your model on "1" samples, you have to set normal data=1 in train and test config files.
RegardsNiousha
    On Saturday, September 5, 2020, 01:34:52 PM GMT+4:30, tiandamiao <notifications@github.com> wrote:  
 
 


In the train, the label of normal data is 1.
In the test, if the input is normal sample, the test loss should be relatively small, and if it is abnormal sample, the test loss should be relatively large. The question is: Why are normal samples labeled 1 instead of 0?
I'm confused about this and hope to get your reply.Thank you!

**Comment by tiandamiao** [comment]
Thank you for your reply. My question is: can the label of normal samples be set to 0, and that of abnormal samples be set to 1? @Niousha12

**Comment by Niousha12** [comment]
I'm not sure that I correctly understood your question. But as a convention, during test phase we will label normal data with 1 and all anomaly data with label 0 (Line 81 to 84 in test.py)I emphasis that it is a convention and you can change it by modifying corresponding linesI think if you want to change your normal data label to 0, anomaly scores must be multiplied by -1 to change its descending order (I should mention that in roc_curve function at (test.py, line 86) pos_labe is set to 0, so it is necessary to your conventions be compatible)Currently i’m too busy but if your problem didn’t solved, i will check it my self and send my exact solution as soon as possible.
RegardsNiousha

    On Saturday, September 5, 2020, 09:01:52 PM GMT+4:30, tiandamiao <notifications@github.com> wrote:  
 
 


Thank you for your reply. My question is: can the label of normal samples be set to 0, and that of abnormal samples be set to 1? @Niousha12

**Comment by SMSD75** [comment]
> I'm not sure that I correctly understood your question. But as a convention, during test phase we will label normal data with 1 and all anomaly data with label 0 (Line 81 to 84 in test.py)I emphasis that it is a convention and you can change it by modifying corresponding linesI think if you want to change your normal data label to 0, anomaly scores must be multiplied by -1 to change its descending order (I should mention that in roc_curve function at (test.py, line 86) pos_labe is set to 0, so it is necessary to your conventions be compatible)Currently i’m too busy but if your problem didn’t solved, i will check it my self and send my exact solution as soon as possible. RegardsNiousha On Saturday, September 5, 2020, 09:01:52 PM GMT+4:30, tiandamiao <notifications@github.com> wrote: Thank you for your reply. My question is: can the label of normal samples be set to 0, and that of abnormal samples be set to 1? @Niousha12 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Because of the specific implementation of the ROC function. you have to set the positive label to your anomalous sample label.
So the choice of 0 or 1 is not arbitrary and you should consider it carefully.
