### ISSUE TITLE
About MVTecAD dataset

### ISSUE THREAD

**Issue by tiandamiao** [Niousha12/Puzzle_Anomaly_Detection#3]
About MVTecAD dataset,I have two question:
1、In testloader, where does the label come from? It's not reflected in the code.
2、In test, what are the anomalous samples for each category? Other categories or defective samples of this category
This is my doubts in the code, I hope to get your reply.Thank you very much. @Niousha12

**Comment by SMSD75** [comment]
> About MVTecAD dataset,I have two question:
> 1、In testloader, where does the label come from? It's not reflected in the code.
> 2、In test, what are the anomalous samples for each category? Other categories or defective samples of this category
> This is my doubts in the code, I hope to get your reply.Thank you very much. @Niousha12

each class of MVTecAD dataset has different a train and test folder. by using "torchvision.datasets.ImageFolder" each class automatically is labeled by its alphabetic order. Then at the test time, one must set the desired target class(alphabetic number of normal class) for its further computations.
