### ISSUE TITLE
Speeding up training process on MVTec 

### ISSUE THREAD

**Issue by LuyuanLi97** [Niousha12/Puzzle_Anomaly_Detection#4]
Hello! I tried to run your code for training on MVTec dataset and find that the training takes a long time. I want to speed up the training process, so I wonder if the performance will be affected if I:
1. Use a larger batch size.
2. Train with the original train set, not expand the dataset into 800.
Looking forward to your reply!

**Comment by Niousha12** [comment]
Hi,




Actually both of these hyperparameters are tuned to increase the performance.

However, the amount of Gpu ram has a direct effect on our selected batch size.

So I suppose increasing batch size according to your Gpu ram space could be a better solution.

Please let me know if my answer wasn't satisfactory enough.




Regards

Niousha



On Monday, December 28, 2020, 7:27 PM, LuyuanLi97 <notifications@github.com> wrote:




Hello! I tried to run your code for training on MVTec dataset and find that the training takes a long time. I want to speed up the training process, so I wonder if the performance will be affected if I:
   
   - Use a larger batch size.
   - Train with the original train set, not expand the dataset into 800.   
Looking forward to your reply!

**Comment by LuyuanLi97** [comment]
Thank you for your advice! I'll try increasing the batch size.
